/*
 *************************************************************************
 * The contents of this file are subject to the Openbravo  Public  License
 * Version  1.1  (the  "License"),  being   the  Mozilla   Public  License
 * Version 1.1  with a permitted attribution clause; you may not  use this
 * file except in compliance with the License. You  may  obtain  a copy of
 * the License at http://www.openbravo.com/legal/license.html 
 * Software distributed under the License  is  distributed  on  an "AS IS"
 * basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
 * License for the specific  language  governing  rights  and  limitations
 * under the License. 
 * The Original Code is Openbravo ERP. 
 * The Initial Developer of the Original Code is Openbravo SLU 
 * All portions are Copyright (C) 2017 Openbravo SLU 
 * All Rights Reserved. 
 * Contributor(s):  ______________________________________.
 ************************************************************************
 */
package org.openbravo.client.kernel;

import org.openbravo.dal.service.OBDal;

/**
 * Classes extending this one will be used by {@link SessionDynamicResourceComponent} to generate
 * the components that should be created before the loading of the javascript content of the
 * application.
 */
public abstract class SessionDynamicTemplateComponent extends BaseTemplateComponent {

  protected abstract String getTemplateId();

  @Override
  protected Template getComponentTemplate() {
    return OBDal.getInstance().get(Template.class, getTemplateId());
  }

  @Override
  public final String getETag() {
    // session dynamic resources do not require an ETag as they are not generated directly in the
    // KernelServlet, they are generated by the SessionDynamicResourceComponent
    return "";
  }
}
