#!/bin/bash
# *************************************************************************
# * The contents of this file are subject to the Openbravo  Public  License
# * Version  1.1  (the  "License"),  being   the  Mozilla   Public  License
# * Version 1.1  with a permitted attribution clause; you may not  use this
# * file except in compliance with the License. You  may  obtain  a copy of
# * the License at http://www.openbravo.com/legal/license.html
# * Software distributed under the License  is  distributed  on  an "AS IS"
# * basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# * License for the specific  language  governing  rights  and  limitations
# * under the License.
# * The Original Code is Openbravo ERP.
# * The Initial Developer of the Original Code is Openbravo SLU
# * All portions are Copyright (C) 2019 Openbravo SLU
# * All Rights Reserved.
# * Contributor(s):  ______________________________________.
# ************************************************************************

#
# Mercurial pretxncommit hook to check linting in js code
#
set -e

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source ${SCRIPT_DIR}/../jsutils/dir-functions

OPENBRAVO_ROOT_PATH=$(getOpenbravoRootPath 2>/dev/null)

if [[ -z "${OPENBRAVO_ROOT_PATH}" ]]; then
    exit 0
fi

IS_A_MODULE=$(isCurrentFolderModuleRoot)

echo "pretxncommit: Performing lint check on modified js resources"

FILES=()
for i in $(hg log -r $HG_NODE --template '{files}')
do
  if [[ -f "${i}" ]]; then
    if [[ "${IS_A_MODULE}" == true && -n "$(echo ${i} | awk '/.js$/')" || \
          "${IS_A_MODULE}" == false && -n "$(echo ${i} | awk '/.js$/ && ! /^web/')" ]]; then
        FILES+=("$(pwd)/${i}")
    fi
  fi
done

if [[ -n "${FILES[*]}" ]]; then
    ${OPENBRAVO_ROOT_PATH}/modules/org.openbravo.client.kernel/jslint/jslint ${FILES[*]} || exit 1
fi

exit 0
