apiVersion: v1
kind: Pod
metadata:
  name: jenkins-node-unittests-orcl-0
  namespace: jenkins2025
  labels:
    app.kubernetes.io/name: jenkins-node-unittests-orcl
spec:
  imagePullSecrets:
    - name: docker-auth-config-secret
  volumes:
    - name: rsa-keys
      configMap:
        name: rsa-keys
        defaultMode: 384
    - name: docker-sock
      hostPath:
        path: /var/run/docker.sock
        type: ''
  containers:
    - name: compiler
      image: etendo/compiler_jenkins:1.0.7-jdk.17.0.13
      ports:
        - name: ssh
          containerPort: 22
          protocol: TCP
        - name: visualvm
          containerPort: 8000
          protocol: TCP
      resources:
        limits:
          cpu: 3072m
          memory: 5000Mi
        requests:
          cpu: 3072m
          memory: 5000Mi
      volumeMounts:
        - name: rsa-keys
          mountPath: /root/.ssh/
        - name: docker-sock
          mountPath: /var/run/docker.sock
      lifecycle:
        postStart:
          exec:
            command:
              - bash
              - '-c'
              - >-
                chmod a+x /var/run/docker.sock && rm
                /etc/apt/sources.list.d/pgdg.list || echo 0 && apt update && apt
                install -y curl
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: IfNotPresent
    - name: oracle
      image: etendo/oracle:19.3.0-ee
      env:
        - name: ORACLE_PWD
          value: oraclepassword
        - name: ORACLE_SID
          value: orclsid
      ports:
        - name: oracle
          containerPort: 1521
          protocol: TCP
        - name: oracle-em
          containerPort: 5500
          protocol: TCP
      resources:
        limits:
          cpu: 2000m
          memory: 6000Mi
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  dnsPolicy: ClusterFirst
  serviceAccountName: default
  serviceAccount: default
  securityContext: {}
