pipeline {
  options {
    disableConcurrentBuilds()
  }

  environment { // MARK: Environment variables
    // gradle.properties variables
    CONTEXT_NAME        = 'etendo'
    BBDD_SID            = 'etendo'
    BBDD_PORT           = '5432'
    BBDD_SYSTEMUSER     = 'postgres'
    BBDD_SYSTEMPASS     = 'syspass'
    BBDD_USER           = 'tad'
    BBDD_PASSWORD       = 'tad'
    NEXUS_USER          = credentials('nexus-admin-user')
    NEXUS_PASSWORD      = credentials('nexus-admin-passwd')
    GITHUB_USER         = 'etendobot'
    GITHUB_TOKEN        = credentials('github-read-package-token')
    LANG                = 'en_US.UTF-8'

    ACCESS_TOKEN        = credentials('access_token_github')
    EMAIL_ADDRESS       = credentials('email_builds')

    URL_REPO            = 'https://github.com/etendosoftware/etendo_core'
    URL_REPO_GIT        = 'git@github.com:etendosoftware/etendo_core.git'

    REPO_NAME           = 'etendo_core'

    SUCCESS             = "SUCCESS"
    FAILED              = "FAILED"
    UNSTABLE            = "UNSTABLE"

    // Stack
    JAVA_HOME           = "/usr/lib/jvm/jdk-17.0.13"
    TOMCAT_URL          = "https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.98/bin/apache-tomcat-9.0.98.tar.gz"
    POSTGRES_VERSION    = "16"

    CONTEXT_BUILD       = "Unit Tests with Postgres Database"

    COMMIT_INPROGRESS_STATUS = "pending"
    COMMIT_SUCCESS_STATUS    = "success"
    COMMIT_FAILED_STATUS     = "failure"

    SONAR_SERVER    = "https://sonar.etendo.cloud"
    SONAR_TOKEN     = credentials('sonar-token')

    TRUE            = "TRUE"
    FALSE           = "FALSE"
  }

  agent { // MARK: Agent
    kubernetes {
      inheritFrom 'jenkins-node-core-unittests'
      defaultContainer 'jnlp'
      yaml """
apiVersion: v1
kind: Pod
metadata:
  name: jenkins-node-core-unittests-0
  namespace: jenkins2025
  labels:
    app.kubernetes.io/name: jenkins-node-core-unittests
spec:
  volumes:
    - name: rsa-keys
      configMap:
        name: rsa-keys
        defaultMode: 384
    - name: docker-sock
      hostPath:
        path: /var/run/docker.sock
        type: ''
  containers:
    - name: compiler
      image: etendo/compiler_jenkins:1.0.7-jdk.17.0.13
      ports:
        - name: ssh
          containerPort: 22
          protocol: TCP
        - name: visualvm
          containerPort: 8000
          protocol: TCP
      resources:
        requests:
          cpu: 1072m
          memory: 4000Mi
        limits:
          cpu: 2072m
          memory: 6000Mi
      volumeMounts:
        - name: rsa-keys
          mountPath: /root/.ssh/
        - name: docker-sock
          mountPath: /var/run/docker.sock
      lifecycle:
        postStart:
          exec:
            command:
              - bash
              - '-c'
              - >-
                chmod a+x /var/run/docker.sock && rm
                /etc/apt/sources.list.d/pgdg.list || echo 0 && apt update && apt
                install -y curl
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: IfNotPresent
    - name: postgres
      image: postgres:16
      workingDir: /home/jenkins
      env:
        - name: POSTGRES_PASSWORD
          value: syspass
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  dnsPolicy: ClusterFirst
  serviceAccountName: default
  serviceAccount: default
  securityContext: {}
"""
    }
  }

  stages { // MARK: Stages
    stage ('Build Environment') { // MARK: Build Environment
      steps {
        container('compiler') {
          script {
            try {
              sh "./pipelines/unittests/build-update.sh ${REPO_NAME} ${COMMIT_INPROGRESS_STATUS} \"Starting Build\" ${ACCESS_TOKEN} ${GIT_COMMIT} ${BUILD_URL} \"${CONTEXT_BUILD}\""

              echo "---------------------- Setting up Environment Variables ----------------------"
              env.EXIST_JACOCO_REPORT = FALSE // Indicates whether the Jacoco report exists (TRUE/FALSE)
              env.STATUSTEST = "1" // Variable to track the status of the test execution. "1" indicates success, "0" indicates failure.
              env.STATUSBUILD = "1" // Variable to track the status of the build. "1" indicates success, "0" indicates failure.
              sh "printenv"

              echo "---------------- Stack Configuration ----------------"
              def rootDir = pwd()
              def stackConfig = load "${rootDir}/pipelines/unittests/utils/stackConfig.groovy"

              sh "wget -O apache-tomcat.tar.gz $TOMCAT_URL"
              sh "tar -xvf apache-tomcat.tar.gz -C $WORKSPACE"

              env.TOMCAT_FOLDER = stackConfig.getTomcatFolder()
              env.CATALINA_HOME = "${WORKSPACE}/${TOMCAT_FOLDER}"
              env.CATALINA_BASE = "${WORKSPACE}/${TOMCAT_FOLDER}"

              env.STACK_INFO = stackConfig.generateStackMessage()
              echo "__________________________________________________"
              echo "${env.STACK_INFO}"
              echo "__________________________________________________"

              withCredentials([sshUserPrivateKey(credentialsId: 'my-credentials', keyFileVariable: 'keyfile')]) {
                sh "GIT_SSH_COMMAND=\"ssh -i ${keyfile} -o \"UserKnownHostsFile=/dev/null\" -o \"StrictHostKeyChecking=no\"\" git clone ${URL_REPO_GIT} ${REPO_NAME}"
              }

              env.WORKDIR_ETENDO = "${pwd()}"

              dir(REPO_NAME) {
                echo "---------------- Getting Commit Information ----------------"
                sh "git checkout ${GIT_COMMIT}"
                def infoCommit = load "${rootDir}/pipelines/unittests/utils/infoCommit.groovy"
                env.COMMIT_INFO = infoCommit.generateCommitInfo(env.URL_REPO)

                echo "--------------- Getting Sonar projectKey of ${REPO_NAME} ---------------"
                def propertiesContent = readFile "sonar-project.properties"
                def lines = propertiesContent.split('\n')
                def projectKey = ""
                lines.each { line ->
                  if (line.startsWith('sonar.projectKey=')) {
                    projectKey = line.split('=')[1]
                  }
                }
                env.PROJECT_KEY = "${projectKey}"


                echo "--------------- Configure gradle.properties ---------------"
                sh """
                echo "\n
                context.name=${CONTEXT_NAME}\n
                bbdd.sid=${BBDD_SID}\n
                bbdd.port=${BBDD_PORT}\n
                bbdd.systemUser=${BBDD_SYSTEMUSER}\n
                bbdd.systemPassword=${BBDD_SYSTEMPASS}\n
                bbdd.user=${BBDD_USER}\n
                bbdd.password=${BBDD_PASSWORD}\n
                nexusUser=${NEXUS_USER}\n
                nexusPassword=${NEXUS_PASSWORD}\n
                githubUser=${GITHUB_USER}\n
                githubToken=${GITHUB_TOKEN}\n
                allow.root=true\n
                org.gradle.jvmargs=-Dfile.encoding=UTF-8\n
                org.gradle.daemon=false
                org.gradle.jvmargs=-XX:MaxHeapSize=1g -Xmx5g

                sonarHostUrl=${SONAR_SERVER}
                sonarToken=${SONAR_TOKEN}
                sonarProjectBaseDir=${WORKDIR_ETENDO}
                sonarProjectName=${REPO_NAME}
                sonarProjectKey=${PROJECT_KEY}
                sonarBranchName=${GIT_BRANCH}
                sonarVersion=${GIT_COMMIT}" > gradle.properties
                """

                def modules_src_dirs = sh(script: "cd modules_core && find . -type d -name 'src' | grep -v 'src-util' | sed 's|./|modules_core/|' | tr '\n' ','", returnStdout: true).trim()
                sh """
                echo "sonarSources=${modules_src_dirs}src" >> gradle.properties
                """

                sh """
                ./gradlew prepareConfig --info
                ./gradlew setup --info
                ./gradlew expandModules --info
                ./gradlew install --info
                ./gradlew update.database  --info
                ./gradlew smartbuild --info
                ./gradlew --stop
                """
              }
              sh "${WORKSPACE}/${TOMCAT_FOLDER}/bin/catalina.sh start"
              sh "sleep 1m"
              echo "--------------- Build Environment Successful ---------------"
            } catch (Exception e) {
              env.ERROR_MESSAGE = "Build Environment Failed"
              echo "--------------- ${env.ERROR_MESSAGE} ---------------"
              echo "Exception occurred: " + e.toString()
              currentBuild.result = FAILED
              error(env.ERROR_MESSAGE)
              env.STATUSBUILD = "0"
              env.STATUSTEST = "0"
            }
          }
        }
      }
    }
// __________________________________________________________________________________________
// ------------------------------ WEB SERVICES TESTS ----------------------------------------
    stage ('Web Service Test Suite') { // MARK: Web Service Test Suite
      when {
        expression {
          env.STATUSBUILD == "1"
        }
      }
      steps {
        sh "./pipelines/unittests/build-update.sh ${REPO_NAME} ${COMMIT_INPROGRESS_STATUS} \"Running Test Suites\" ${ACCESS_TOKEN} ${GIT_COMMIT} ${BUILD_URL} \"${CONTEXT_BUILD}\""
        container('compiler') {
          script {
            dir(REPO_NAME) {
              try {
                echo "--------------- Running WebserviceTestSuite ---------------"
                sh "./gradlew test --tests org.openbravo.test.WebserviceTestSuite --info"
                sh "mv build/jacoco/test.exec build/jacoco/test0.exec"
                echo "--------------- WebserviceTestSuite Successful ---------------"
                currentBuild.result = SUCCESS
              } catch (Exception e) {
                echo "--------------- WebserviceTestSuite Failed ---------------"
                echo 'Exception occurred: ' + e.toString()
                currentBuild.result = UNSTABLE
                unstable('WebservicesTestSuite Failed')
                env.STATUSTEST = "0"
              } finally {
                if (fileExists("build/reports/tests/test/")) {
                  publishHTML([
                    allowMissing: true,
                    alwaysLinkToLastBuild: false,
                    keepAll: true,
                    reportDir: 'build/reports/tests/test',
                    reportFiles: '*.html',
                    reportName: 'WEBSERVICES TESTS REPORT',
                    reportTitles: ''
                  ])
                  sh "rm -rf build/reports/tests/test"
                } else {
                 echo "Report directory of Webservices tests does not exist. Skipping HTML report publishing."
                }
                sh "${WORKSPACE}/${TOMCAT_FOLDER}/bin/catalina.sh stop"
                sh "./gradlew --stop"
              }
            }
          }
        }
      }
    }
// __________________________________________________________________________________________
// ------------------------------ com.smf.* TESTS ------------------------------------------
    stage ('Core Test Suite') { // MARK: CoreTestSuite Test Suite
      when {
        expression {
          env.STATUSBUILD == "1"
        }
      }
      steps {
        container('compiler') {
          script {
            dir(REPO_NAME) {
              try {
                echo "--------------- Running CoreTestSuite ---------------"
                sh "./gradlew test --tests com.smf.test.CoreTestSuite --info"
                sh "mv build/jacoco/test.exec build/jacoco/test1.exec"
                echo "--------------- CoreTestSuite Successful ---------------"
                currentBuild.result = SUCCESS
              } catch (Exception e) {
                echo "--------------- CoreTestSuite Failed ---------------"
                echo 'Exception occurred: ' + e.toString()
                currentBuild.result = UNSTABLE
                unstable('CoreTestSuite Failed')
                env.STATUSTEST = "0"
              } finally {
                if (fileExists("build/reports/tests/test/")) {
                  publishHTML([
                    allowMissing: false,
                    alwaysLinkToLastBuild: false,
                    keepAll: true,
                    reportDir: 'build/reports/tests/test',
                    reportFiles: '*.html',
                    reportName: 'com.smf.* TESTS REPORT',
                    reportTitles: ''
                  ])
                  sh "rm -rf build/reports/tests/test"
                } else {
                  echo "Report directory of com.smf.* tests does not exist. Skipping HTML report publishing."
                }

              }
            }
          }
        }
      }
    }
// __________________________________________________________________________________________
// ------------------------------- STANDALONE TESTS -----------------------------------------
    stage ('Standalone Test Suite') { // MARK: Standalone Test Suite
      when {
        expression {
          env.STATUSBUILD == "1"
        }
      }
      steps {
        container('compiler') {
          script {
            dir(REPO_NAME) {
              try {
                echo "--------------- Running StandaloneTestSuite ---------------"
                sh "./gradlew test --tests org.openbravo.test.StandaloneTestSuite --info"
                sh "mv build/jacoco/test.exec build/jacoco/test2.exec"
                echo "--------------- StandaloneTestSuite Successful ---------------"
                currentBuild.result = SUCCESS
              } catch (Exception e) {
                echo "--------------- StandaloneTestSuite Failed ---------------"
                echo 'Exception occurred: ' + e.toString()
                currentBuild.result = UNSTABLE
                unstable('StandaloneTestSuite Failed')
                env.STATUSTEST = "0"
              } finally {
                if (fileExists("build/reports/tests/test/")) {
                  publishHTML([
                    allowMissing: true,
                    alwaysLinkToLastBuild: false,
                    keepAll: true,
                    reportDir: 'build/reports/tests/test',
                    reportFiles: '*.html',
                    reportName: 'STANDALONE TESTS REPORT',
                    reportTitles: ''
                  ])
                  sh "rm -rf build/reports/tests/test"
                } else {
                  echo "Report directory of Standalone tests does not exist. Skipping HTML report publishing."
                }
              }
            }
          }
        }
      }
    }
// __________________________________________________________________________________________
// ----------------------------------- com.etendoerp.* TESTS --------------------------------
    stage ('com.etendoerp.* Tests') { // MARK: com.etendoerp.* Test
      when {
        expression {
          env.STATUSBUILD == "1"
        }
      }
      steps {
        container('compiler') {
          script {
            dir(REPO_NAME) {
              try {
                echo "--------------- Running com.etendoerp.* Tests ---------------"
                sh "./gradlew test --tests \"com.etendoerp.*\" --info"
                sh "mv build/jacoco/test.exec build/jacoco/test3.exec"
                sh "./gradlew --stop"
                echo "--------------- com.etendoerp.* Tests Successful ---------------"
                currentBuild.result = SUCCESS
              } catch (Exception e) {
                echo "--------------- com.etendoerp.* Tests Failed ---------------"
                echo 'Exception occurred: ' + e.toString()
                currentBuild.result = UNSTABLE
                unstable('com.etendoerp.* Tests failed!')
                env.STATUSTEST = "0"
              } finally {
                if (fileExists('build/spock-reports/')) {
                  publishHTML([
                    allowMissing: true,
                    alwaysLinkToLastBuild: false,
                    keepAll: true,
                    reportDir: 'build/spock-reports/',
                    reportFiles: '*.html',
                    reportName: 'com.etendoerp.* SPOCK TESTS REPORT',
                    reportTitles: ''
                  ])
                  sh "rm -rf build/spock-reports"
                } else {
                  echo "Spock report directory of com.etendoerp.* tests does not exist. Skipping HTML report publishing."
                }

                if (fileExists('build/reports/tests/test/')) {
                  publishHTML([
                    allowMissing: true,
                    alwaysLinkToLastBuild: false,
                    keepAll: true,
                    reportDir: 'build/reports/tests/test',
                    reportFiles: '*.html',
                    reportName: 'com.etendoerp.* TESTS REPORT',
                    reportTitles: ''
                  ])
                  sh "rm -rf build/reports/tests/test"
                } else {
                  echo "Report directory of com.etendoerp.* tests does not exist. Skipping HTML report publishing."
                }
              }
            }
          }
        }
      }
    }
// __________________________________________________________________________________________
// ----------------------------------- JACOCO REPORT ----------------------------------------
    stage('Generate Coverage Report') { // MARK: Generate Coverage Report
      when {
        expression {
          env.STATUSTEST == "1"
        }
      }
      steps {
        container("compiler") {
          script {
            sh "./pipelines/unittests/build-update.sh ${REPO_NAME} ${COMMIT_INPROGRESS_STATUS} \"Generating JaCoCo report\" ${ACCESS_TOKEN} ${GIT_COMMIT} ${BUILD_URL} \"${CONTEXT_BUILD}\""
            echo "---------------------- Run jacocoRootReport ----------------------"
            sh """
            su etendo
            cd ${REPO_NAME}
            ./gradlew jacocoRootReport --info
            """

            env.JACOCO_REPORT = "${REPO_NAME}/build/reports/jacoco/jacocoRootReport/jacocoRootReport.xml"

            if (fileExists("${JACOCO_REPORT}")) {
              echo "---------------------- Jacoco Report Found ----------------------"
              env.EXIST_JACOCO_REPORT = TRUE
            }
          }
        }
      }
    }
// __________________________________________________________________________________________
// ----------------------------------- SONARQUBE ANALYSIS -----------------------------------
    stage('SonarQube Analysis') { // MARK: SonarQube Analysis
      when {
        expression {
          EXIST_JACOCO_REPORT == TRUE
        }
      }
      steps {
        container('compiler') {
          script {
            try {
              sh "./pipelines/unittests/build-update.sh ${REPO_NAME} ${COMMIT_INPROGRESS_STATUS} \"Running SonarQube Analysis\" ${ACCESS_TOKEN} ${GIT_COMMIT} ${BUILD_URL} \"${CONTEXT_BUILD}\""

              def modulesCoreExclusions = [
                "com.smf.userinterface.skin.legacy",
                "org.openbravo.client.widgets",
                "org.openbravo.client.htmlwidget",
                "com.smf.smartclient.debugtools",
                "org.openbravo.client.myob",
                "org.openbravo.userinterface.smartclient",
                "com.smf.smartclient.boostedui",
                "com.etendoerp.client.application"
              ]

              def sourceExclusions = modulesCoreExclusions.collect { "modules_core/${it}/**" }.join(',')

              echo "---------------------- Add deprecated classes to sourceExclusions list ----------------------"
              def deprecatedFiles = sh(
                  script: '''
                    cd ${REPO_NAME}
                    find . -name "*.java" -exec grep -l '@Deprecated' {} + | while read file; do
                      if grep -A1 '@Deprecated' "$file" | grep -q 'public class'; then
                        echo "$file"
                      fi
                    done
                  ''',
                  returnStdout: true
              ).trim().split('\n')

              def deprecatedExclusions = deprecatedFiles.collect { it.replaceFirst("^\\./", "") }.join(',')
              sourceExclusions = "${sourceExclusions},${deprecatedExclusions}"

              echo "Sources to exclusions: ${sourceExclusions}"

              echo "--------------- Running SonarQube ---------------"
              sh """
              su etendo
              cd ${REPO_NAME}
              ./gradlew sonar -Dsonar.inclusions=**/*.java -Dsonar.exclusions=${sourceExclusions} --stacktrace --info
              """
              echo "---------------------- Getting SonarQube Report URL ----------------------"
              def branchName = URLEncoder.encode(GIT_BRANCH, 'UTF-8')
              def projectUrl = "${SONAR_SERVER}/dashboard?id=${PROJECT_KEY}&branch=${branchName}"
              env.PROJECT_URL = "${projectUrl}"
              echo "Sonar Project URL: ${PROJECT_URL}"
              echo "--------------- Execution SonarQube Succesful ---------------"
              currentBuild.result = SUCCESS
            } catch (Exception e) {
              env.ERROR_MESSAGE = "Execution SonarQube Failed"
              echo "--------------- ${env.ERROR_MESSAGE} ---------------"
              echo "Exception occurred: " + e.toString()
              currentBuild.result = FAILED
              error(env.ERROR_MESSAGE)
            }
          }
        }
      }
    }

// __________________________________________________________________________________________
// ----------------------------------- DEPLOY SNAPSHOT --------------------------------------
    stage('Run Deploy Snapshot') { // MARK: Run Deploy Snapshot
      when {
        allOf {
          anyOf {
            branch 'develop'
          }
          expression {
              env.STATUSTEST == "1"
          }
        }
      }
      steps {
        container('compiler') {
          script {
            try {
              sh "./pipelines/unittests/build-update.sh ${REPO_NAME} ${COMMIT_INPROGRESS_STATUS} \"Deploying Snapshot\" ${ACCESS_TOKEN} ${GIT_COMMIT} ${BUILD_URL} \"${CONTEXT_BUILD}\""
              echo "--------------- Running Deploy Snapshot ---------------"
              dir(REPO_NAME) {
                withCredentials([sshUserPrivateKey(credentialsId: 'my-credentials', keyFileVariable: 'keyfile')]) {
                  withCredentials([usernamePassword(credentialsId: "etendo_bot_credentials", passwordVariable: 'GIT_PASSWORD', usernameVariable: 'GIT_USERNAME')]) {
                      sh """
                      git config user.name "${GIT_USERNAME}"
                      git config user.email "${GIT_USERNAME}"
                      """
                      sh "echo version.ts=\$(date +\"%s\") > version.properties"
                      sh "./gradlew publishCoreJar --info"
                      sh "git tag \"v\$(grep version.ts version.properties|cut -c 11-)\" -m \"Release SNAPSHOT \$(grep version.tag version.properties|cut -c 13-)\""
                      sh "GIT_SSH_COMMAND=\"ssh -i ${keyfile} -o \"UserKnownHostsFile=/dev/null\" -o \"StrictHostKeyChecking=no\"\" git push ${GIT_URL} \"v\$(grep version.ts version.properties|cut -c 11-)\""
                  }
                }
              }
            } catch (Exception e) {
              env.ERROR_MESSAGE = "Deploy Snapshot Failed"
              echo "--------------- ${env.ERROR_MESSAGE} ---------------"
              echo "Exception occurred: " + e.toString()
              currentBuild.result = FAILED
              error(env.ERROR_MESSAGE)
            }
          }
        }
      }
    }
  }
  post {  // MARK: Post Actions
    success {
        script {
            sh "./pipelines/unittests/build-update.sh ${REPO_NAME} ${COMMIT_SUCCESS_STATUS} \"Successful Test Suites\" ${ACCESS_TOKEN} ${GIT_COMMIT} ${BUILD_URL} \"${CONTEXT_BUILD}\""
            echo "--------------- DONE ---------------"
        }
    }
    fixed {
      mail to: EMAIL_ADDRESS,
      subject: "✅ FIXED - ${currentBuild.fullDisplayName}",
      mimeType: "text/html",
      body:  """
        <html>
          <head>
              <style>
                  body { font-family: 'Arial', sans-serif; }
                  .header { font-size: 16px; font-weight: bold; color: #333; }
              </style>
          </head>
          <body>
            <p><em>${new Date()}</em></p>
            <p>__________________________________________________________</p>

            <h2 class="header">✅ ERRORS FIXED ✅</h2>

            ${env.COMMIT_INFO}

            ${env.STACK_INFO}

            <p>The problems found in the previous run/s have been fixed! 💪<br>Check out the output in the following link: ${env.BUILD_URL}</p>

            <p class="footer"><em>Best regards,<br>#EtendoBot 🤖</em></p>
            <p>__________________________________________________________</p>
          </body>
        </html>
      """
    }
    unstable {
      script {
        sh "./pipelines/unittests/build-update.sh ${REPO_NAME} ${COMMIT_FAILED_STATUS} \"Unstable Test Suites\" ${ACCESS_TOKEN} ${GIT_COMMIT} ${BUILD_URL} \"${CONTEXT_BUILD}\""
            echo "--------------- UNSTABLE ---------------"
      }
      mail to: EMAIL_ADDRESS,
      subject: "⚠️ TESTS FAILED - ${currentBuild.fullDisplayName}",
      mimeType: "text/html",
      body:  """
        <html>
          <head>
              <style>
                  body { font-family: 'Arial', sans-serif; }
                  .header { font-size: 16px; font-weight: bold; color: #333; }
              </style>
          </head>
          <body>
            <p><em>${new Date()}</em></p>
            <p>__________________________________________________________</p>

            <h2 class="header">⚠️ BUILD UNSTABLE ⚠️</h2>

            ${env.COMMIT_INFO}

            ${env.STACK_INFO}

            <p>Tests have been detected that have failed in Etendo Core.<br>To more information on the failing run visit: ${env.BUILD_URL}</p>

            <p class="footer"><em>Best regards,<br>#EtendoBot 🤖</em></p>
            <p>__________________________________________________________</p>
          </body>
        </html>
      """
    }
    failure {
      script {
        sh "./pipelines/unittests/build-update.sh ${REPO_NAME} ${COMMIT_FAILED_STATUS} \"${ERROR_MESSAGE}\" ${ACCESS_TOKEN} ${GIT_COMMIT} ${BUILD_URL} \"${CONTEXT_BUILD}\""
        echo "--------------- FAILURE ---------------"
      }
      mail to: EMAIL_ADDRESS,
      subject: "⛔ ERROR - ${currentBuild.fullDisplayName}",
      mimeType: "text/html",
      body:  """
        <html>
          <head>
              <style>
                  body { font-family: 'Arial', sans-serif; }
                  .header { font-size: 16px; font-weight: bold; color: #333; }
              </style>
          </head>
          <body>
            <p><em>${new Date()}</em></p>
            <p>__________________________________________________________</p>

            <h2 class="header">🚫 BUILD FAILED 🚫</h2>

            ${env.COMMIT_INFO}

            ${env.STACK_INFO}

            <p><strong>⇢ Reasons:</strong> <em>${env.ERROR_MESSAGE}</em></p>
            <p>To more information on the failing run visit: ${env.BUILD_URL}</p>

            <p class="footer"><em>Best regards,<br>#EtendoBot 🤖</em></p>
            <p>__________________________________________________________</p>
          </body>
        </html>
      """
    }
  }
}
