name: Auto Reviewer

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  make-review:
    runs-on: ubuntu-latest
    env:
      PULL_REQUEST: ${{ github.event.pull_request.number }}
      PROJECT: ${{ github.event.repository.owner.login }}
      REPO_SLUG: ${{ github.event.repository.name }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      ETENDOBOT_TOKEN: ${{ secrets.ETENDOBOT_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Debug
        run: |
          echo ${{ env.OPENAI_API_KEY }}
          echo ${{ env.ETENDOBOT_TOKEN }}
          echo "-------------------------------------------------------------------------"

      - name: Run Docker container
        id: run-docker
        run: |
          printenv
          echo "-------------------------------------------------------------------------"
          if [ -z "${{ env.OPENAI_API_KEY }}" ]; then
            echo "OPENAI_API_KEY está vacía"
          else
            echo "OPENAI_API_KEY tiene un valor"
          fi
          echo "-------------------------------------------------------------------------"
          docker run -d -p 5000:5000 -e REPO_API_TOKEN="${{ env.ETENDOBOT_TOKEN }}" -e PULL_REQUEST=${{ env.PULL_REQUEST }} -e PROJECT=${{ env.PROJECT }} -e REPO_SLUG=${{ env.REPO_SLUG }} -e OPENAI_API_KEY="${{ env.OPENAI_API_KEY }}" etendo/code-reviewer:latest
          export CONTAINER_ID=$(docker ps -qf "ancestor=etendo/code-reviewer:latest")
      
      - name: Make Reviewer API call
        id: call-api
        run: |
          sleep 10s
          response=$(curl -s -o response.txt -w "%{http_code}" -X GET http://localhost:5000/review/github)
          if [ $response -ne 200 ]; then
            echo "API call failed with status code $response"
            export CONTAINER_ID=$(docker ps -qf "ancestor=etendo/code-reviewer:latest")
            docker logs $CONTAINER_ID
            echo "Response text:"
            cat response.txt
            exit 1
          fi
          echo "API call successful with status code $response"
          echo "Response text:"
          cat response.txt