name: "Snyk Code Scan"

on:
  push:
    branches:
      - main
      - develop
  workflow_run:
    workflows: [Git Police]
    types: [completed]

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: snyk/actions/setup@master
      - name: Snyk Code Test
        continue-on-error: true
        run: snyk code test --sarif > snyk_sarif
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Upload results to Github Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk_sarif
